name: Deploy Docs

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:



build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      # Install Dependenices
      - run: bun install
      # Run the API
      - run: bun start
      # Add to NGINX
      - run: mv . teaclientmc/api
      - run: cp -R teaclientmc/api /home/tea/sites/api
